# Generated by Django 4.0.5 on 2022-07-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='like', to='network.post'),
        ),
    ]
