# Generated by Django 4.0.5 on 2022-07-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_auctionlisting_watchlist_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='WatchListSize',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
