# Generated by Django 4.0.5 on 2022-07-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_comment_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='category',
            field=models.CharField(blank=True, choices=[('', 'None'), ('Home', 'Home'), ('Sport', 'Sport'), ('Car', 'Car'), ('Electronics', 'Electronics'), ('Other', 'Other')], max_length=256),
        ),
    ]
